[workspace]
members = [
    "call-contract",
    "decode-signed-eth-tx",
    "multi-threading",
    "multi-threading-mpsc",
    "multi-threading-sharedmem", "multizip",
    "native-time",
    "readcsv",
    "sqlx-batch-update",
    "structs",
    "time-elapse"
]

resolver = "2"
